

const EMAIL_SENDED = "EMAIL_SENDED"  ;
const USERNOT_FOUND = "USERNOT_FOUND"  ;
const FORGOT_REQUEST = "FORGOT_REQUEST" ; 
const PASSWORD_CHANGE_REQUEST = "PASSWORD_CHANGE_REQUEST" ;
const PASSSWORD_CHANGE    = "PASSSWORD_CHANGE"  ;
const INVALID_CODE =       "INVALID_CODE"      ;
 
export {
    EMAIL_SENDED ,
     USERNOT_FOUND , 
     FORGOT_REQUEST ,
     PASSWORD_CHANGE_REQUEST,
      PASSSWORD_CHANGE ,
      INVALID_CODE
}